name: Create release

on:
  push:
    branches: ['main']

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Automatic Release Creation
        uses: lr0pb/generate-release@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fallback-text: 'No text'
